### ISSUE TITLE
Bug : Zod input schema validation fix required on input fields.

### ISSUE THREAD

**Issue by adityadeshlahre** [uninbox/UnInbox#13]
Hey contributor :wave: 
currently: In few place input validation is broken. [Empty Spaces OR White Spaces can be entered/updated]

1. Profile Page
![image](https://github.com/uninbox/UnInbox/assets/132184385/3af65eaf-4b84-44eb-9982-ab8535d71554)

2. Invite Page
![image](https://github.com/uninbox/UnInbox/assets/132184385/61c0b15d-c15d-4660-9ecb-202bbce6b995)

3. Add Group Component
![image](https://github.com/uninbox/UnInbox/assets/132184385/357d27d1-9537-485f-91a4-7e4f06d12b8f)

4. Add New Email Address Page
![image](https://github.com/uninbox/UnInbox/assets/132184385/4d71f3d6-8cbe-4d2a-8a31-f6b9789887e2)

[please check in other places too]

Update Request : Show throw Errors in below the input fields OR Should show TOAST messages .

like this one below [ only on page based field (not on the components) ]
&
[on components just need to show error below input fields ]
![image](https://github.com/uninbox/UnInbox/assets/132184385/7e8002e9-3851-4d38-b137-81161a99af7d)

**Comment by McPizza0** [comment]
we currently use zod for input field schema validation
I think it accepts a SPACE as a string character
would need to find a way to ensure that SPACE is not the first character

**Comment by McPizza0** [comment]
sure @skushagra9 
looks like z.string().trim()..... would work on the inputs that have validation
you can search the codebase for instances of the UnUiInput component, and test if .trim() fixes the issue

**Comment by skushagra9** [comment]
sure, thanks

**Comment by McPizza0** [comment]
The toast errors are the response from the server - should stay as they are
it should never get to that point since we do client side validation first

if we see the zod schema error in a toast, it means there is something wrong in the code and we need to check the local schema validation to match what the server expects
