### ISSUE TITLE
domainDetails page: update data to use Accordion

### ISSUE THREAD

**Issue by McPizza0** [uninbox/UnInbox#17]
Page: https://github.com/uninbox/UnInbox/blob/main/apps/web-app/pages/%5BorgSlug%5D/settings/org/mail/domains/%5BdomainId%5D.vue

to view the page in action, you need to add a domain.

This page uses a custom accordion that was created before we switched to NuxtUI library

NuxtUI has a nice accordion component: https://ui.nuxt.com/elements/accordion#multiple
we will need to replace the current badges with the already existing UnUiBadge component

The Accordion should render the same data that exists now

reach out on discord if you have any questions

**Comment by skushagra9** [comment]
I would like to work on this

**Comment by McPizza0** [comment]
sure!
