### ISSUE TITLE
feat(web): create email templates for transactional email

### ISSUE THREAD

**Issue by McPizza0** [uninbox/UnInbox#22]
we use vue-email for email templating and need some transactional email templates created

these are the needed emails and their props:

verify recovery email
props: {
username: string;
verification code: string;
verification link: string;
}

login code
props: {
username: string;
login code: string;
}

invite
props: {
inviterName: string;
inviterAvatarId: string
orgName: string;
orgAvatarId: string;
inviteCode: string;
expiryDate: datetime;
}

templates should be created in apps/web-app/emails
the folder contains a vercel email that can be used as a template

be sure to check https://vuemail.net/ docs

**Comment by adityadeshlahre** [comment]
Let me give it a shot :smiley: !
