### ISSUE TITLE
overflow X is not handled on the main landing page 

### ISSUE THREAD

**Issue by professssor** [uninbox/UnInbox#3]
At [https://uninbox.com/](url) , the x-axis data is overflowing a few pixels , showing a ugly scroll bar on the horizontal axis , 
it can be easily rectified easily with simple CSS ,

**Comment by dhananjay0610** [comment]
Hi, can you please assign it to me

**Comment by McPizza0** [comment]
Thanks @professssor , very well spotted!

The current production landing page is temporary and due to be replaced soon.

So this issue will be addressed in the new page.

Closing for now
