### ISSUE TITLE
when a user creates or joins a new org, create new profile

### ISSUE THREAD

**Issue by McPizza0** [uninbox/UnInbox#42]
I thought this was already implemented, but a user has a profile per organization
when creating a new org, or joining a new one as an existing user, we should duplicate their current profile and create a new one for the user

currently the users existing profile is used

**Comment by skushagra9** [comment]
I am interested to work on this, please assign this to me

**Comment by McPizza0** [comment]
looks to be here on line 108
`/apps/web-app/server/trpc/routers/orgRouter/orgCrudRouter.ts`
we would need to use the existing profile to create a new one, then use the id of the new one for all subsequent queries

**Comment by skushagra9** [comment]
yes, its taking the newProfilePublicId as the default value
