### ISSUE TITLE
when uploading avatar, storage server has error and new avatar not rendered on page

### ISSUE THREAD

**Issue by McPizza0** [uninbox/UnInbox#43]
when uploading a new avatar, the upload does succeed and the image is accessible
but the avatar on the page does not refresh to new value

<details>
<summary>prev error (fixed)</summary>
the storage server logs out an error
```
@uninbox/storage:dev: [nitro] [uncaughtException] TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object
@uninbox/storage:dev:     at write_ (node:_http_outgoing:879:11)
@uninbox/storage:dev:     at ServerResponse.end (node:_http_outgoing:1030:5)
@uninbox/storage:dev:     at Immediate.<anonymous> (file:///Users/omar/code/UnInbox/node_modules/.pnpm/h3@1.10.1/node_modules/h3/dist/index.mjs:682:24)
@uninbox/storage:dev:     at process.processImmediate (node:internal/timers:478:21) {
@uninbox/storage:dev:   code: 'ERR_INVALID_ARG_TYPE'
@uninbox/storage:dev: }
```

</details>
Error is fixed by https://github.com/uninbox/UnInbox/pull/48

**Comment by Praashh** [comment]
I think, This could be due to incorrect handling of the data during processing or transmission, can I work on this issue or someone from team is already working upon that?

**Comment by McPizza0** [comment]
@Praashh you currently have another issue assigned

**Comment by skushagra9** [comment]
Hey , I am interested to solve this issue

**Comment by McPizza0** [comment]
the error will be fixed by https://github.com/uninbox/UnInbox/pull/48
otherwise the avatar refresh is good to go

**Comment by McPizza0** [comment]
we should also add:
`refreshNuxtData('getUserSingleProfileNav')` & `refreshNuxtData('getUserOrgsNav')` to the end of the `selectedFilesOnChange` functions when saving the profiles for users & orgs respectivly
this will refresh the avatars in the main app nav menu
![image](https://github.com/uninbox/UnInbox/assets/17185737/d012e632-c370-45d1-973c-28665905453a)

**Comment by skushagra9** [comment]
can I work on this, as pending triage label is still there
?
