### ISSUE TITLE
When Creating New Group, It shows error and nuxt freezes and doesn't navigates to pages anymore

### ISSUE THREAD

**Issue by skushagra9** [uninbox/UnInbox#52]
query is returning the correct data and the data pushing is also working fine

**Comment by skushagra9** [comment]
issue is with: 
![image](https://github.com/uninbox/UnInbox/assets/120712705/f8a56066-6579-47be-8213-7ab2533059a8)

If I remove the 
:rows="tableRows"
All the functionality works fine
So the problem lies with the tableRows

**Comment by McPizza0** [comment]
yeah, looks like it could be some data within the table itself failing
breaking rendering across the app

**Comment by skushagra9** [comment]
ok I am checking it

**Comment by McPizza0** [comment]
looks to be an issue with the avatar-id prop on line 117
looking into it

**Comment by skushagra9** [comment]
its returning null

**Comment by skushagra9** [comment]
I found something in avatar.post there is some error I guess

**Comment by skushagra9** [comment]
on line num 99 and 112 in avatar.post

**Comment by McPizza0** [comment]
continuing in discord
