### ISSUE TITLE
Draft: Save user device (name/type) in session data

### ISSUE THREAD

**Issue by McPizza0** [uninbox/UnInbox#60]
When generating user session - we should pass in the user's device (type/name) and browser.

This will be stored in the session data, and used to give users an easy way to manage their sessions from the UI

examples:
google
![image](https://github.com/uninbox/UnInbox/assets/17185737/30e4dd5c-b2b2-45e0-a643-bd244181b3a8)

 notes:
 - using `user-agent` is not reliable since all chromium browser report as chrome
 - Arc browser can be detected client side using `getComputedStyle(document.documentElement).getPropertyValue('--arc-palette-title') ? 'Is Arc' : 'Is Not Arc'`
 - Brave browser can be detected client side using `!navigator.brave` or `typeof navigator?.brave?.isBrave === 'function'`
 - We need a way to detect if the user is using the PWA, this may be possible through a custom user-agent

**Comment by ezra-en** [comment]
We could use fingerprinting solutions, but is it worth the potential privacy violations to have this feature? 
We could just go off of naive device names and allow for user-configured nicknames for the devices, but that doesn't really address the issue at hand: how does this apparently non-trivial feature contribute to the larger product vision?

**Comment by McPizza0** [comment]
> We could use fingerprinting solutions

yeah 100% want to avoid that due to privacy stuffs

> how does this apparently non-trivial feature contribute to the larger product vision?

security will be given quite a bit of focus, at least the decisions around them
allowing users to manage their sessions is a must
and the device name / browser name are a big UX boost without tracking IP addresses or user locations

renaming is a good thing to add 👍

**Comment by McPizza0** [comment]
implementing this as part of the new auth system
so far we are just getting the users `device` and `os`

these will be saved in the session data

**Comment by ezra-en** [comment]
Does Lucia give us nice utils to accomplish this or do we still have to parse user agents?

**Comment by McPizza0** [comment]
still need to parse user agents manually

implemented in #79
