### ISSUE TITLE
landing page faq contains two entries about encryption

### ISSUE THREAD

**Issue by McPizza0** [uninbox/UnInbox#68]
![image](https://github.com/uninbox/UnInbox/assets/17185737/084cd11a-8519-4a83-9be2-1ce3444201f2)

the text from these should be consolidated into one single entry that carries the same meaning from both

**Comment by adityadeshlahre** [comment]
taking this one :slightly_smiling_face:

**Comment by WaitWhatJustHappened** [comment]
@McPizza0 This issue has been closed as completed, but you can still see two entries instead of one merged entry.

**Comment by McPizza0** [comment]
huh
ill re-deploy, thanks

**Comment by McPizza0** [comment]
done
