### ISSUE TITLE
Update landing site "OSS-Friends" page

### ISSUE THREAD

**Issue by McPizza0** [uninbox/UnInbox#72]
File location: `apps/landing-page/pages/oss-friends.vue`

This page is part of a  Open Source projects network
The current page was made quite a while ago and never updated

The design of the page should be updated to use components from NuxtUi: https://ui.nuxt.com/getting-started
Heres some inspirations; https://documenso.com/oss-friends https://www.hanko.io/oss-friends https://infisical.com/infisical-friends

To get the data, we need to query the api located at `https://formbricks.com/api/oss-friends`

The link to the oss-page should be added to the `Footer` component

Finally, we should set the route rule to cache the page with a ttl of 24 hours (swr mode): https://nuxt.com/docs/guide/concepts/rendering#route-rules

**Comment by McPizza0** [comment]
yes, thats the idea

**Comment by skushagra9** [comment]
Got it, thanks
