### ISSUE TITLE
Minor grammatical mistakes on landing FAQs

### ISSUE THREAD

**Issue by WaitWhatJustHappened** [uninbox/UnInbox#73]
**Q:** Can I use UnInbox for my personal email?
**A:** Yes, most of our features are designed for collaboration, but everything should work `if its just you.`
**Suggestion:** Yes, most of our features are designed for collaboration, but everything should work `even if it's just you.`

---

**Q:** Why are custom domains not available on the free plan?
**A:** There is a high risk of spam and abuse with custom domains, and this could `damage the all our sending infrastructure.` We require a paid plan as verification and to cover the additional technical requirements of ensuring safe email sending across our platform.
**Suggestion:** There is a high risk of spam and abuse with custom domains, and this could `damage our infrastructure.` We require a paid plan as verification and to cover the additional technical requirements of ensuring safe email sending across our platform.

---

**Q:** Will you have a calendar?
**A:** `It's planned, but will come after the email app is stable.`
**Suggestion:** `Our initial focus is ensuring the stability of the email app and a seamless experience for its users. We'll introduce new features, including the calendar, once the app is stable.`

---

**Q:** Can I migrate my emails from Google or another provider?
**Q:** We `want` to make De-Googling and migrating from `other providers` super easy. `Its not yet possible but its on our priorities list.`
**Suggestion:** We `aim` to make De-Googling and migrating from `other email service providers` super easy. `While it's not possible yet, it's on our list of priorities.`

---

**Q:** Will your prices ever increase?
**A:** `Yes, as time goes on things become more expensive. BUT, when you have an active subscription, the price is locked in till your subscription expires.`
**Suggestion:** `Yes, over time, prices may increase due to rising costs. However, if you have an active subscription, your price will be locked in until your subscription expires.`

---

**Q:** Can I use UnInbox with another email client?
**A:** No, we are built on very different technologies and `theres` simply no way to make them compatible. If you really need to use another email client, check for another service or use our forwarding feature.
**Suggestion:** No, we are built on very different technologies and `there's` simply no way to make them compatible. If you really need to use another email client, check for another service or use our forwarding feature.

---

**Q:** Can I forward `mail in from another service?`
**A:** Yes, you get a personal email address with UnInbox, and a dedicated forwarding address. Any emails sent to your forwarding address will appear in your UnInbox. You can also forward all emails for a custom domain to your UnInbox organization.
**Suggestion:** Can I forward `emails from another email service provider?`

---

**Q:** Will you do what Skiff did and abandon us?
**A:** No, we do not plan on getting acquired, that's not our end goal. If we were ever to shut down, our code will remain freely available for you to self-host and we will take some steps to `ensure the online platform can remain active.`
**Suggestion:** No, we do not plan on getting acquired, that's not our end goal. If we were ever to shut down, our code will remain freely available for you to self-host and we will take some steps to `ensure that the online platform will remain active.`

**Comment by WaitWhatJustHappened** [comment]
@McPizza0 I created a PR to address the above issue. Please feel free to review and merge/decline.

**Comment by McPizza0** [comment]
closed by #74

**Comment by McPizza0** [comment]
@WaitWhatJustHappened Congrats on your first even open source contribution 🎉
send me a DM on twitter or in the discord ❤️

**Comment by WaitWhatJustHappened** [comment]
@McPizza0 Hey, thanks! I will. 🙂

Btw, just one last thing while we are on the topic of FAQs, shouldn’t there be a question about 2FA? This is definitely one of the first few things that any security / privacy focused enthusiast will notice and ask about.

**Comment by WaitWhatJustHappened** [comment]
Brilliant. Perhaps you should consider adding it to the FAQs.
