### ISSUE TITLE
Landing page favicon is still the default Nuxt favicon

### ISSUE THREAD

**Issue by ezra-en** [uninbox/UnInbox#75]
🖤
The favicon for the landing page is still the default Nuxt favicon.
![Uploading Screenshot 2024-02-16 at 2.46.33 AM.png…]()

**Comment by McPizza0** [comment]
i see it as the correct "U"
![image](https://github.com/uninbox/UnInbox/assets/17185737/5d8ed908-a113-40c4-8485-26c9f206f335)

can you share which browser you're using?

**Comment by McPizza0** [comment]
ah i see it now
seems I changed it in one branch but didnt push to main 😂
