### ISSUE TITLE
When adding a group, should be able to add email identity for the group in the same modal

### ISSUE THREAD

**Issue by McPizza0** [uninbox/UnInbox#9]
Currently:
When adding a new group, you can enter the name, description and color via the add new group modal
new modal file path: `./apps/web-app/components/settings/addNewGroup.vue`
![image](https://github.com/uninbox/UnInbox/assets/17185737/5c406322-d129-4b14-9f1e-8052a10a4c56)

We need to add a toggle to also create an email identity for the group, based on the add new email modal

All the logic and inputs already exist, see add new email modal for code: `./apps/web-app/components/settings/addNewEmail.vue`
the new toggleable input options should be: address, domain and send name.  reuse the same input validation that currently exists. the group should be set as the "deliver messages to".

we should re-use the same trpc endpoint that creates email identities to avoid duplicating backend logic/code: `$trpc.org.mail.emailIdentities.createNewEmailIdentity`

--

If you want to work on this, please tag me

**Comment by adityadeshlahre** [comment]
Hey @McPizza0 giving it a try :smiley: !

**Comment by McPizza0** [comment]
Perfect!

**Comment by aditya172001** [comment]
Hey @McPizza0 I'd like to work on it.

**Comment by McPizza0** [comment]
hey @aditya172001 
@adityadeshlahre is currently working on it
lets checkin next week if the issue is still open and it can be assigned to you

**Comment by skushagra9** [comment]
Hey, I have figured out the solution, Please assign to me if it is not solved.

**Comment by adityadeshlahre** [comment]
Hey @McPizza0 sorry for the delay in response !

@skushagra9 Nice see that u have figured out solution already !

but since @aditya172001 came before you with the comment.
he should get get chance to solve it and yeah @aditya172001 go ahead on solving the issue

@skushagra9 u can proceed after @aditya172001 : )

Thank You :smiley:

**Comment by McPizza0** [comment]
@adityadeshlahre just to confirm, you no longer want to work on this issue?

**Comment by McPizza0** [comment]
closed by https://github.com/uninbox/UnInbox/pull/15
